[package]
name = "ssd1351"
version = "0.1.0"
authors = ["Scott <MabezDev@gmail.com>"]

[dependencies]

[dependencies.embedded-hal]
version = "0.2.1"
features = ["unproven"]

[dev-dependencies.stm32l4]
version = "0.2.1"
features = ["stm32l4x2", "rt"]

[dev-dependencies.stm32l432xx-hal]
git = "https://github.com/MabezDev/stm32l432xx-hal"
# branch = "pll"
# path = "../../hal/stm32l432xx-hal"

[dev-dependencies]
panic-semihosting = "0.3.0"
cortex-m-semihosting = "0.3.0"
cortex-m = "0.5.2"
nb = "0.1.1"
cortex-m-rt = "0.5.1"

[profile.dev]
incremental = false
codegen-units = 1

[profile.release]
codegen-units = 1
debug = true
lto = true
